import 'package:flutter/material.dart';
import 'package:pit_app/Qrpage.dart';
import 'homepage.dart';
import 'page1.dart';

void main() {
  runApp(
    const MaterialApp(
      title: '4903 Pit Scouting App', // used by the OS task switcher
      home: MyScaffold(),
    ),
  );
}

class MyScaffold extends StatefulWidget {
  const MyScaffold({super.key});

  @override
  State<MyScaffold> createState() => ScaffoldState();
}

class ScaffoldState extends State<MyScaffold> {
//😬 i mean it works so...
  var inputs = {
    'refnum': '',
    'num': '',
    'teamnum': '',
    'visited1': false,
    'weight1': '',
    'length1': '',
    'width1': '',
    'other1': '',
    'comments1': '',
    'swerve1': false,
    'tank1': false,
    'mecanum1': false,
    'otherbox1': false,
    'team1': '610',
    'teamname1': 'Crescent Coyotes',
    'visited2': false,
    'weight2': '',
    'length2': '',
    'width2': '',
    'other2': '',
    'comments2': '',
    'swerve2': false,
    'tank2': false,
    'mecanum2': false,
    'otherbox2': false,
    'team2': '865',
    'teamname2': 'WARP7',
    'visited3': false,
    'weight3': '',
    'length3': '',
    'width3': '',
    'other3': '',
    'comments3': '',
    'swerve3': false,
    'tank3': false,
    'mecanum3': false,
    'otherbox3': false,
    'team3': '1114',
    'teamname3': 'Simbotics',
    'visited4': false,
    'weight4': '',
    'length4': '',
    'width4': '',
    'other4': '',
    'comments4': '',
    'swerve4': false,
    'tank4': false,
    'mecanum4': false,
    'otherbox4': false,
    'team4': '1285',
    'teamname4': 'The Biggest Birds',
    'visited5': false,
    'weight5': '',
    'length5': '',
    'width5': '',
    'other5': '',
    'comments5': '',
    'swerve5': false,
    'tank5': false,
    'mecanum5': false,
    'otherbox5': false,
    'team5': '1310',
    'teamname5': 'Runnymede Robotics',
    'visited6': false,
    'weight6': '',
    'length6': '',
    'width6': '',
    'other6': '',
    'comments6': '',
    'swerve6': false,
    'tank6': false,
    'mecanum6': false,
    'otherbox6': false,
    'team6': '1325',
    'teamname6': 'Inverse Paradox',
    'visited7': false,
    'weight7': '',
    'length7': '',
    'width7': '',
    'other7': '',
    'comments7': '',
    'swerve7': false,
    'tank7': false,
    'mecanum7': false,
    'otherbox7': false,
    'team7': '1334',
    'teamname7': 'Red Devils',
    'visited8': false,
    'weight8': '',
    'length8': '',
    'width8': '',
    'other8': '',
    'comments8': '',
    'swerve8': false,
    'tank8': false,
    'mecanum8': false,
    'otherbox8': false,
    'team8': '2013',
    'teamname8': 'Cybergnomes',
    'visited9': false,
    'weight9': '',
    'length9': '',
    'width9': '',
    'other9': '',
    'comments9': '',
    'swerve9': false,
    'tank9': false,
    'mecanum9': false,
    'otherbox9': false,
    'team9': '2386',
    'teamname9': 'Trojans',
    'visited10': false,
    'weight10': '',
    'length10': '',
    'width10': '',
    'other10': '',
    'comments10': '',
    'swerve10': false,
    'tank10': false,
    'mecanum10': false,
    'otherbox10': false,
    'team10': '2609',
    'teamname10': 'BeaverworX',
    'visited11': false,
    'weight11': '',
    'length11': '',
    'width11': '',
    'other11': '',
    'comments11': '',
    'swerve11': false,
    'tank11': false,
    'mecanum11': false,
    'otherbox11': false,
    'team11': '2706',
    'teamname11': 'Merge Robotics',
    'visited12': false,
    'weight12': '',
    'length12': '',
    'width12': '',
    'other12': '',
    'comments12': '',
    'swerve12': false,
    'tank12': false,
    'mecanum12': false,
    'otherbox12': false,
    'team12': '2708',
    'teamname12': 'Lake Effect Robotics',
    'visited13': false,
    'weight13': '',
    'length13': '',
    'width13': '',
    'other13': '',
    'comments13': '',
    'swerve13': false,
    'tank13': false,
    'mecanum13': false,
    'otherbox13': false,
    'team13': '3739',
    'teamname13': 'Oakbotics',
    'visited14': false,
    'weight14': '',
    'length14': '',
    'width14': '',
    'other14': '',
    'comments14': '',
    'swerve14': false,
    'tank14': false,
    'mecanum14': false,
    'otherbox14': false,
    'team14': '4039',
    'teamname14': 'MakeShift Robotics',
    'visited15': false,
    'weight15': '',
    'length15': '',
    'width15': '',
    'other15': '',
    'comments15': '',
    'swerve15': false,
    'tank15': false,
    'mecanum15': false,
    'otherbox15': false,
    'team15': '4069',
    'teamname15': 'Lo-Ellen Robotics',
    'visited16': false,
    'weight16': '',
    'length16': '',
    'width16': '',
    'other16': '',
    'comments16': '',
    'swerve16': false,
    'tank16': false,
    'mecanum16': false,
    'otherbox16': false,
    'team16': '4343',
    'teamname16': 'MaxTech',
    'visited17': false,
    'weight17': '',
    'length17': '',
    'width17': '',
    'other17': '',
    'comments17': '',
    'swerve17': false,
    'tank17': false,
    'mecanum17': false,
    'otherbox17': false,
    'team17': '4678',
    'teamname17': 'CyberCavs',
    'visited18': false,
    'weight18': '',
    'length18': '',
    'width18': '',
    'other18': '',
    'comments18': '',
    'swerve18': false,
    'tank18': false,
    'mecanum18': false,
    'otherbox18': false,
    'team18': '4688',
    'teamname18': 'Saints Bot',
    'visited19': false,
    'weight19': '',
    'length19': '',
    'width19': '',
    'other19': '',
    'comments19': '',
    'swerve19': false,
    'tank19': false,
    'mecanum19': false,
    'otherbox19': false,
    'team19': '4903',
    'teamname19': 'Mustangs',
    'visited20': false,
    'weight20': '',
    'length20': '',
    'width20': '',
    'other20': '',
    'comments20': '',
    'swerve20': false,
    'tank20': false,
    'mecanum20': false,
    'otherbox20': false,
    'team20': '4907',
    'teamname20': 'Thunderstamps',
    'visited21': false,
    'weight21': '',
    'length21': '',
    'width21': '',
    'other21': '',
    'comments21': '',
    'swerve21': false,
    'tank21': false,
    'mecanum21': false,
    'otherbox21': false,
    'team21': '4917',
    'teamname21': 'Sir Lancerbot',
    'visited22': false,
    'weight22': '',
    'length22': '',
    'width22': '',
    'other22': '',
    'comments22': '',
    'swerve22': false,
    'tank22': false,
    'mecanum22': false,
    'otherbox22': false,
    'team22': '4920',
    'teamname22': 'Belle River Boltheads',
    'visited23': false,
    'weight23': '',
    'length23': '',
    'width23': '',
    'other23': '',
    'comments23': '',
    'swerve23': false,
    'tank23': false,
    'mecanum23': false,
    'otherbox23': false,
    'team23': '4946',
    'teamname23': 'The Alpha Dogs',
    'visited24': false,
    'weight24': '',
    'length24': '',
    'width24': '',
    'other24': '',
    'comments24': '',
    'swerve24': false,
    'tank24': false,
    'mecanum24': false,
    'otherbox24': false,
    'team24': '5024',
    'teamname24': 'Raider Robotics',
    'visited25': false,
    'weight25': '',
    'length25': '',
    'width25': '',
    'other25': '',
    'comments25': '',
    'swerve25': false,
    'tank25': false,
    'mecanum25': false,
    'otherbox25': false,
    'team25': '5036',
    'teamname25': 'The Robo Devils',
    'visited26': false,
    'weight26': '',
    'length26': '',
    'width26': '',
    'other26': '',
    'comments26': '',
    'swerve26': false,
    'tank26': false,
    'mecanum26': false,
    'otherbox26': false,
    'team26': '5596',
    'teamname26': 'Wolverines',
    'visited27': false,
    'weight27': '',
    'length27': '',
    'width27': '',
    'other27': '',
    'comments27': '',
    'swerve27': false,
    'tank27': false,
    'mecanum27': false,
    'otherbox27': false,
    'team27': '5870',
    'teamname27': 'League of Logic',
    'visited28': false,
    'weight28': '',
    'length28': '',
    'width28': '',
    'other28': '',
    'comments28': '',
    'swerve28': false,
    'tank28': false,
    'mecanum28': false,
    'otherbox28': false,
    'team28': '5885',
    'teamname28': 'Villanova WiredCats',
    'visited29': false,
    'weight29': '',
    'length29': '',
    'width29': '',
    'other29': '',
    'comments29': '',
    'swerve29': false,
    'tank29': false,
    'mecanum29': false,
    'otherbox29': false,
    'team29': '6378',
    'teamname29': 'LYNX',
    'visited30': false,
    'weight30': '',
    'length30': '',
    'width30': '',
    'other30': '',
    'comments30': '',
    'swerve30': false,
    'tank30': false,
    'mecanum30': false,
    'otherbox30': false,
    'team30': '6854',
    'teamname30': 'Viking Robotics',
    'visited31': false,
    'weight31': '',
    'length31': '',
    'width31': '',
    'other31': '',
    'comments31': '',
    'swerve31': false,
    'tank31': false,
    'mecanum31': false,
    'otherbox31': false,
    'team31': '6864',
    'teamname31': 'Gryphtech Robotics',
    'visited32': false,
    'weight32': '',
    'length32': '',
    'width32': '',
    'other32': '',
    'comments32': '',
    'swerve32': false,
    'tank32': false,
    'mecanum32': false,
    'otherbox32': false,
    'team32': '6865',
    'teamname32': 'Manitoulin Metal 6865',
    'visited33': false,
    'weight33': '',
    'length33': '',
    'width33': '',
    'other33': '',
    'comments33': '',
    'swerve33': false,
    'tank33': false,
    'mecanum33': false,
    'otherbox33': false,
    'team33': '6987',
    'teamname33': 'Falcon Automation',
    'visited34': false,
    'weight34': '',
    'length34': '',
    'width34': '',
    'other34': '',
    'comments34': '',
    'swerve34': false,
    'tank34': false,
    'mecanum34': false,
    'otherbox34': false,
    'team34': '7476',
    'teamname34': 'Aureus',
    'visited35': false,
    'weight35': '',
    'length35': '',
    'width35': '',
    'other35': '',
    'comments35': '',
    'swerve35': false,
    'tank35': false,
    'mecanum35': false,
    'otherbox35': false,
    'team35': '7690',
    'teamname35': 'Ironworks Robotics',
    'visited36': false,
    'weight36': '',
    'length36': '',
    'width36': '',
    'other36': '',
    'comments36': '',
    'swerve36': false,
    'tank36': false,
    'mecanum36': false,
    'otherbox36': false,
    'team36': '7722',
    'teamname36': 'Resurrection MechaPhoenix',
    'visited37': false,
    'weight37': '',
    'length37': '',
    'width37': '',
    'other37': '',
    'comments37': '',
    'swerve37': false,
    'tank37': false,
    'mecanum37': false,
    'otherbox37': false,
    'team37': '7757',
    'teamname37': 'Atomic Dishwashers',
    'visited38': false,
    'weight38': '',
    'length38': '',
    'width38': '',
    'other38': '',
    'comments38': '',
    'swerve38': false,
    'tank38': false,
    'mecanum38': false,
    'otherbox38': false,
    'team38': '8729',
    'teamname38': 'Sparkling H2O',
    'visited39': false,
    'weight39': '',
    'length39': '',
    'width39': '',
    'other39': '',
    'comments39': '',
    'swerve39': false,
    'tank39': false,
    'mecanum39': false,
    'otherbox39': false,
    'team39': '8764',
    'teamname39': 'Thunder Robotics',
    'visited40': false,
    'weight40': '',
    'length40': '',
    'width40': '',
    'other40': '',
    'comments40': '',
    'swerve40': false,
    'tank40': false,
    'mecanum40': false,
    'otherbox40': false,
    'team40': '9263',
    'teamname40': 'ALD Lions',
    'visited41': false,
    'weight41': '',
    'length41': '',
    'width41': '',
    'other41': '',
    'comments41': '',
    'swerve41': false,
    'tank41': false,
    'mecanum41': false,
    'otherbox41': false,
    'team41': '',
    'teamname41': 'EXTRA',
  };

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '4903 Pit Scouting App',
      theme: ThemeData(primarySwatch: Colors.blue, brightness: Brightness.dark),
      initialRoute: '/',
      routes: {
        '/': (context) => HomePage(
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/Qrpage': (context) => Qrcode(inputs: inputs),
        '/page1': (context) => Page1(
            teamnum: 1,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page2': (context) => Page1(
            teamnum: 2,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page3': (context) => Page1(
            teamnum: 3,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page4': (context) => Page1(
            teamnum: 4,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page5': (context) => Page1(
            teamnum: 5,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page6': (context) => Page1(
            teamnum: 6,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page7': (context) => Page1(
            teamnum: 7,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page8': (context) => Page1(
            teamnum: 8,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page9': (context) => Page1(
            teamnum: 9,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page10': (context) => Page1(
            teamnum: 10,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page11': (context) => Page1(
            teamnum: 11,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page12': (context) => Page1(
            teamnum: 12,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page13': (context) => Page1(
            teamnum: 13,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page14': (context) => Page1(
            teamnum: 14,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page15': (context) => Page1(
            teamnum: 15,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page16': (context) => Page1(
            teamnum: 16,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page17': (context) => Page1(
            teamnum: 17,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page18': (context) => Page1(
            teamnum: 18,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page19': (context) => Page1(
            teamnum: 19,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page20': (context) => Page1(
            teamnum: 20,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page21': (context) => Page1(
            teamnum: 21,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page22': (context) => Page1(
            teamnum: 22,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page23': (context) => Page1(
            teamnum: 23,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page24': (context) => Page1(
            teamnum: 24,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page25': (context) => Page1(
            teamnum: 25,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page26': (context) => Page1(
            teamnum: 26,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page27': (context) => Page1(
            teamnum: 27,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page28': (context) => Page1(
            teamnum: 28,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page29': (context) => Page1(
            teamnum: 29,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page30': (context) => Page1(
            teamnum: 30,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page31': (context) => Page1(
            teamnum: 31,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page32': (context) => Page1(
            teamnum: 32,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page33': (context) => Page1(
            teamnum: 33,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page34': (context) => Page1(
            teamnum: 34,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page35': (context) => Page1(
            teamnum: 35,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page36': (context) => Page1(
            teamnum: 36,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page37': (context) => Page1(
            teamnum: 37,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page38': (context) => Page1(
            teamnum: 38,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page39': (context) => Page1(
            teamnum: 39,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page40': (context) => Page1(
            teamnum: 40,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page41': (context) => Page1(
            teamnum: 41,
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
      },
    );
  }
}
