import 'package:flutter/material.dart';
import 'package:pit_app/Qrpage.dart';
import 'homepage.dart';
import 'page1.dart';

void main() {
  runApp(
    const MaterialApp(
      title: '4903 Pit Scouting App', // used by the OS task switcher
      home: MyScaffold(),
    ),
  );
}

class MyScaffold extends StatefulWidget {
  const MyScaffold({super.key});

  @override
  State<MyScaffold> createState() => ScaffoldState();
}

class ScaffoldState extends State<MyScaffold> {
//😬 i mean it works so...
  var inputs = {
    'refnum': '',
    'num': '',
    'teamnum': '',
    'visited1': false,
    'weight1': '',
    'length1': '',
    'width1': '',
    'other1': '',
    'comments1': '',
    'swerve1': false,
    'tank1': false,
    'mecanum1': false,
    'otherbox1': false,
    'team1': '772',
    'teamname1': 'Sabre Bytes Robotics',
    'visited2': false,
    'weight2': '',
    'length2': '',
    'width2': '',
    'other2': '',
    'comments2': '',
    'swerve2': false,
    'tank2': false,
    'mecanum2': false,
    'otherbox2': false,
    'team2': '854',
    'teamname2': 'Iron Bears',
    'visited3': false,
    'weight3': '',
    'length3': '',
    'width3': '',
    'other3': '',
    'comments3': '',
    'swerve3': false,
    'tank3': false,
    'mecanum3': false,
    'otherbox3': false,
    'team3': '2198',
    'teamname3': 'Paradigm Shift Robotics',
    'visited4': false,
    'weight4': '',
    'length4': '',
    'width4': '',
    'other4': '',
    'comments4': '',
    'swerve4': false,
    'tank4': false,
    'mecanum4': false,
    'otherbox4': false,
    'team4': '2634',
    'teamname4': 'The Gryphons',
    'visited5': false,
    'weight5': '',
    'length5': '',
    'width5': '',
    'other5': '',
    'comments5': '',
    'swerve5': false,
    'tank5': false,
    'mecanum5': false,
    'otherbox5': false,
    'team5': '2852',
    'teamname5': 'DM High Voltage',
    'visited6': false,
    'weight6': '',
    'length6': '',
    'width6': '',
    'other6': '',
    'comments6': '',
    'swerve6': false,
    'tank6': false,
    'mecanum6': false,
    'otherbox6': false,
    'team6': '3560',
    'teamname6': 'Chingbotics',
    'visited7': false,
    'weight7': '',
    'length7': '',
    'width7': '',
    'other7': '',
    'comments7': '',
    'swerve7': false,
    'tank7': false,
    'mecanum7': false,
    'otherbox7': false,
    'team7': '4308',
    'teamname7': 'ABSOLUTE ROBOTICS',
    'visited8': false,
    'weight8': '',
    'length8': '',
    'width8': '',
    'other8': '',
    'comments8': '',
    'swerve8': false,
    'tank8': false,
    'mecanum8': false,
    'otherbox8': false,
    'team8': '4617',
    'teamname8': 'DAUN',
    'visited9': false,
    'weight9': '',
    'length9': '',
    'width9': '',
    'other9': '',
    'comments9': '',
    'swerve9': false,
    'tank9': false,
    'mecanum9': false,
    'otherbox9': false,
    'team9': '4678',
    'teamname9': 'CyberCavs',
    'visited10': false,
    'weight10': '',
    'length10': '',
    'width10': '',
    'other10': '',
    'comments10': '',
    'swerve10': false,
    'tank10': false,
    'mecanum10': false,
    'otherbox10': false,
    'team10': '4688',
    'teamname10': 'Saints Bot',
    'visited11': false,
    'weight11': '',
    'length11': '',
    'width11': '',
    'other11': '',
    'comments11': '',
    'swerve11': false,
    'tank11': false,
    'mecanum11': false,
    'otherbox11': false,
    'team11': '4903',
    'teamname11': 'Mustangs',
    'visited12': false,
    'weight12': '',
    'length12': '',
    'width12': '',
    'other12': '',
    'comments12': '',
    'swerve12': false,
    'tank12': false,
    'mecanum12': false,
    'otherbox12': false,
    'team12': '4907',
    'teamname12': 'Thunderstamps',
    'visited13': false,
    'weight13': '',
    'length13': '',
    'width13': '',
    'other13': '',
    'comments13': '',
    'swerve13': false,
    'tank13': false,
    'mecanum13': false,
    'otherbox13': false,
    'team13': '4920',
    'teamname13': 'Belle River Boltheads',
    'visited14': false,
    'weight14': '',
    'length14': '',
    'width14': '',
    'other14': '',
    'comments14': '',
    'swerve14': false,
    'tank14': false,
    'mecanum14': false,
    'otherbox14': false,
    'team14': '4940',
    'teamname14': 'Knight Vision',
    'visited15': false,
    'weight15': '',
    'length15': '',
    'width15': '',
    'other15': '',
    'comments15': '',
    'swerve15': false,
    'tank15': false,
    'mecanum15': false,
    'otherbox15': false,
    'team15': '4946',
    'teamname15': 'The Alpha Dogs',
    'visited16': false,
    'weight16': '',
    'length16': '',
    'width16': '',
    'other16': '',
    'comments16': '',
    'swerve16': false,
    'tank16': false,
    'mecanum16': false,
    'otherbox16': false,
    'team16': '4951',
    'teamname16': 'CDS Cyclones',
    'visited17': false,
    'weight17': '',
    'length17': '',
    'width17': '',
    'other17': '',
    'comments17': '',
    'swerve17': false,
    'tank17': false,
    'mecanum17': false,
    'otherbox17': false,
    'team17': '5024',
    'teamname17': 'Raider Robotics',
    'visited18': false,
    'weight18': '',
    'length18': '',
    'width18': '',
    'other18': '',
    'comments18': '',
    'swerve18': false,
    'tank18': false,
    'mecanum18': false,
    'otherbox18': false,
    'team18': '5408',
    'teamname18': 'KENNEDYcache',
    'visited19': false,
    'weight19': '',
    'length19': '',
    'width19': '',
    'other19': '',
    'comments19': '',
    'swerve19': false,
    'tank19': false,
    'mecanum19': false,
    'otherbox19': false,
    'team19': '5596',
    'teamname19': 'Wolverines',
    'visited20': false,
    'weight20': '',
    'length20': '',
    'width20': '',
    'other20': '',
    'comments20': '',
    'swerve20': false,
    'tank20': false,
    'mecanum20': false,
    'otherbox20': false,
    'team20': '5885',
    'teamname20': 'Villanova WiredCats',
    'visited21': false,
    'weight21': '',
    'length21': '',
    'width21': '',
    'other21': '',
    'comments21': '',
    'swerve21': false,
    'tank21': false,
    'mecanum21': false,
    'otherbox21': false,
    'team21': '5912',
    'teamname21': 'Heritage Robotics',
    'visited22': false,
    'weight22': '',
    'length22': '',
    'width22': '',
    'other22': '',
    'comments22': '',
    'swerve22': false,
    'tank22': false,
    'mecanum22': false,
    'otherbox22': false,
    'team22': '6070',
    'teamname22': 'Gryphon Machine',
    'visited23': false,
    'weight23': '',
    'length23': '',
    'width23': '',
    'other23': '',
    'comments23': '',
    'swerve23': false,
    'tank23': false,
    'mecanum23': false,
    'otherbox23': false,
    'team23': '6110',
    'teamname23': 'Doc Botics',
    'visited24': false,
    'weight24': '',
    'length24': '',
    'width24': '',
    'other24': '',
    'comments24': '',
    'swerve24': false,
    'tank24': false,
    'mecanum24': false,
    'otherbox24': false,
    'team24': '6162',
    'teamname24': 'Cap Alpaca 6162',
    'visited25': false,
    'weight25': '',
    'length25': '',
    'width25': '',
    'other25': '',
    'comments25': '',
    'swerve25': false,
    'tank25': false,
    'mecanum25': false,
    'otherbox25': false,
    'team25': '6632',
    'teamname25': 'Northview Robotics',
    'visited26': false,
    'weight26': '',
    'length26': '',
    'width26': '',
    'other26': '',
    'comments26': '',
    'swerve26': false,
    'tank26': false,
    'mecanum26': false,
    'otherbox26': false,
    'team26': '6725',
    'teamname26': 'Westminster WildBOTS',
    'visited27': false,
    'weight27': '',
    'length27': '',
    'width27': '',
    'other27': '',
    'comments27': '',
    'swerve27': false,
    'tank27': false,
    'mecanum27': false,
    'otherbox27': false,
    'team27': '6875',
    'teamname27': 'Amazon Warriors - Build A Dream Robotics',
    'visited28': false,
    'weight28': '',
    'length28': '',
    'width28': '',
    'other28': '',
    'comments28': '',
    'swerve28': false,
    'tank28': false,
    'mecanum28': false,
    'otherbox28': false,
    'team28': '7136',
    'teamname28': 'Thistletown Scot Bots',
    'visited29': false,
    'weight29': '',
    'length29': '',
    'width29': '',
    'other29': '',
    'comments29': '',
    'swerve29': false,
    'tank29': false,
    'mecanum29': false,
    'otherbox29': false,
    'team29': '8081',
    'teamname29': 'UMEI Lightning Robotics',
    'visited30': false,
    'weight30': '',
    'length30': '',
    'width30': '',
    'other30': '',
    'comments30': '',
    'swerve30': false,
    'tank30': false,
    'mecanum30': false,
    'otherbox30': false,
    'team30': '8574',
    'teamname30': 'Audeamus',
  };

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '4903 Pit Scouting App',
      theme: ThemeData(primarySwatch: Colors.blue, brightness: Brightness.dark),
      initialRoute: '/',
      routes: {
        '/': (context) => HomePage(
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/Qrpage': (context) => Qrcode(inputs: inputs),
        '/page1': (context) => Page1(
            teamnum: 1,
            teamname: 'team 1',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page2': (context) => Page1(
            teamnum: 2,
            teamname: 'team 2',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page3': (context) => Page1(
            teamnum: 3,
            teamname: 'team 3',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page4': (context) => Page1(
            teamnum: 4,
            teamname: 'team 4',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page5': (context) => Page1(
            teamnum: 5,
            teamname: 'team 5',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page6': (context) => Page1(
            teamnum: 6,
            teamname: 'team 6',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page7': (context) => Page1(
            teamnum: 7,
            teamname: 'team 7',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page8': (context) => Page1(
            teamnum: 8,
            teamname: 'team 8',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page9': (context) => Page1(
            teamnum: 9,
            teamname: 'team 9',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page10': (context) => Page1(
            teamnum: 10,
            teamname: 'team 10',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page11': (context) => Page1(
            teamnum: 11,
            teamname: 'team 11',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page12': (context) => Page1(
            teamnum: 12,
            teamname: 'team 12',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page13': (context) => Page1(
            teamnum: 13,
            teamname: 'team 13',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page14': (context) => Page1(
            teamnum: 14,
            teamname: 'team 14',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page15': (context) => Page1(
            teamnum: 15,
            teamname: 'team 15',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page16': (context) => Page1(
            teamnum: 16,
            teamname: 'team 16',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page17': (context) => Page1(
            teamnum: 17,
            teamname: 'team 17',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page18': (context) => Page1(
            teamnum: 18,
            teamname: 'team 18',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page19': (context) => Page1(
            teamnum: 19,
            teamname: 'team 19',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page20': (context) => Page1(
            teamnum: 20,
            teamname: 'team 20',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page21': (context) => Page1(
            teamnum: 21,
            teamname: 'team 21',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page22': (context) => Page1(
            teamnum: 22,
            teamname: 'team 22',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page23': (context) => Page1(
            teamnum: 23,
            teamname: 'team 23',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page24': (context) => Page1(
            teamnum: 24,
            teamname: 'team 24',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page25': (context) => Page1(
            teamnum: 25,
            teamname: 'team 25',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page26': (context) => Page1(
            teamnum: 26,
            teamname: 'team 26',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page27': (context) => Page1(
            teamnum: 27,
            teamname: 'team 27',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page28': (context) => Page1(
            teamnum: 28,
            teamname: 'team 28',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page29': (context) => Page1(
            teamnum: 29,
            teamname: 'team 29',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
        '/page30': (context) => Page1(
            teamnum: 30,
            teamname: 'team 30',
            inputs: inputs,
            callback: (value) => setState(() => inputs = value)),
      },
    );
  }
}
